<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Title>FTOptixNetPlugin.Tools</Title>
	  <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	  <Authors>Renyi</Authors>
	  <Company></Company>
	  <Product />
	  <Description></Description>
	  <PackageProjectUrl></PackageProjectUrl>
	  <PackageTags>FTOptix;.Net;Tools</PackageTags>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <RepositoryUrl>https://github.com/ren1987yi/FTOptixNetPlugin.git</RepositoryUrl>
	  <Version>0.0.0.1</Version>
  </PropertyGroup>
<Import Project="FTOptixNetPlugin.Tools.references" />
</Project>
